# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'MJRefresh', '~> 3.1.15.3'
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.2.0'
pod 'SDWebImage', '~> 4.3.3'
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'YYCategories', '~> 1.0.4'
pod 'SVProgressHUD', '~> 2.2.5'
  # Pods for reader

end
